apiVersion: bitcoin.kiln-fired.github.io/v1alpha1
kind: BitcoinNode
metadata:
  name: miner
spec:
  image:
    btcdImage: 'quay.io/kiln-fired/btcd:latest'
    btcdTimerImage: 'quay.io/kiln-fired/btcd:latest'
  mining:
    cpuMiningEnabled: false
    rewardAddress:
      secretName: alice-address
    minBlocks: 400
    periodicBlocksEnabled: true
    secondsPerBlock: 10
  rpcServer:
    certSecret: miner-rpc-tls
    apiAuthSecretName: btcd-rpc-creds
    apiUserSecretKey: username
    apiPasswordSecretKey: password