apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miner-rpc-tls
spec:
  secretName: miner-rpc-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  commonName: miner
  usages:
    - server auth
  dnsNames:
  - miner
  - miner.kiln-demo.svc
  - miner.kiln-demo.svc.cluster.local
  - localhost
  keyEncoding: pkcs8
