apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: simnet-node-rpc-tls
spec:
  secretName: simnet-node-rpc-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  commonName: simnet-node
  usages:
    - server auth
  dnsNames:
  - simnet-node
  - simnet-node.kiln-demo.svc
  - simnet-node.kiln-demo.svc.cluster.local
  - localhost
  keyEncoding: pkcs8
