apiVersion: bitcoin.kiln-fired.github.io/v1alpha1
kind: BitcoinNode
metadata:
  name: alice-peer
spec:
  image:
    btcdImage: 'quay.io/kiln-fired/btcd:latest'
  mining:
    cpuMiningEnabled: false
    rewardAddress:
      secretName: alice-address
  rpcServer:
    certSecret: alice-peer-rpc-tls
    apiAuthSecretName: alice-peer-rpc-creds
    apiUserSecretKey: username
    apiPasswordSecretKey: password
  peer: 'miner:18555'