apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alice-peer-rpc-tls
spec:
  secretName: alice-peer-rpc-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  commonName: alice-peer
  usages:
    - server auth
  dnsNames:
  - alice-peer
  - alice-peer.kiln-demo.svc
  - alice-peer.kiln-demo.svc.cluster.local
  - localhost
  keyEncoding: pkcs8
